# Generated by Django 5.1.15 on 2026-07-29 15:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=30, verbose_name='활동 종류')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='값이 올바르지 않습니다.'), django.core.validators.MaxValueValidator(Decimal('0.99'), message='값이 올바르지 않습니다.')], verbose_name='환산율')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity',
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0), ('rate__lt', 1)), name='rate_between_0_and_1')],
            },
        ),
    ]
