# Generated by Django 5.1.15 on 2026-07-28 12:01

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='값이 올바르지 않습니다.'), django.core.validators.MaxValueValidator(Decimal('0.99'), message='값이 올바르지 않습니다.')], verbose_name='환산율'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0), ('rate__lt', 1)), name='rate_between_0_and_1'),
        ),
    ]
