# Generated by Django 5.2.4 on 2026-08-11 12:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'), message='값이 올바르지 않습니다.'), django.core.validators.MaxValueValidator(Decimal('0.9999'), message='값이 올바르지 않습니다.')], verbose_name='환산율'),
        ),
    ]
