# Generated by Django 5.2.4 on 2026-08-01 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(verbose_name='마감 날짜')),
                ('closed_at', models.DateTimeField(verbose_name='마감 일시')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_close',
                'unique_together': {('users', 'close_date')},
            },
        ),
        migrations.CreateModel(
            name='EarnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn_min', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='적립 분')),
                ('verify_method', models.CharField(max_length=10, verbose_name='인증 방식')),
                ('photo_url', models.TextField(blank=True, null=True, verbose_name='인증 사진 URL')),
                ('earn_date', models.DateField(verbose_name='적립 날짜')),
                ('earn_start', models.DateTimeField(verbose_name='시작 시각')),
                ('earn_end', models.DateTimeField(verbose_name='종료 시각')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earn_records', to='budget.activity')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'earn_record',
                'indexes': [models.Index(fields=['users', 'earn_date'], name='earn_record_users_i_1e0664_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_date', models.DateField(verbose_name='지출 날짜')),
                ('category', models.CharField(max_length=30, verbose_name='카테고리')),
                ('duration_min', models.IntegerField(verbose_name='지속 시간(분)')),
                ('spend_start', models.DateTimeField(verbose_name='시작 시각')),
                ('spend_end', models.DateTimeField(verbose_name='종료 시각')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spend_record',
                'indexes': [models.Index(fields=['users', 'spend_date'], name='spend_recor_users_i_44e688_idx')],
            },
        ),
    ]
