# Generated by Django 5.1.15 on 2026-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyclose',
            name='closed_at',
            field=models.DateTimeField(verbose_name='마감 일시'),
        ),
    ]
