# Generated by Django 5.2.4 on 2026-08-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_activity_is_active'),
        ('ledger', '0002_earnrecord_created_at_spendrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnrecord',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_records', to='budget.activity'),
        ),
    ]
