# Generated by Django 5.2.4 on 2026-08-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='kakao_id',
        ),
        migrations.AddField(
            model_name='users',
            name='conversion_unit',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='환산단위'),
        ),
        migrations.AddField(
            model_name='users',
            name='converting_activity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='환산활동'),
        ),
    ]
