# Generated by Django 5.1.15 on 2026-07-28 12:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conversion_base',
            field=models.DecimalField(decimal_places=4, default=0, help_text='지출 시간(분)을 금액·책 권수 등으로 변환할 때 곱하는 비율', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'), message='값이 올바르지 않습니다.')], verbose_name='환산 비율'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekly_budget_min',
            field=models.DecimalField(decimal_places=2, default=210, max_digits=10, verbose_name='주간 예산(분)'),
        ),
    ]
