# Generated by Django 5.2.4 on 2026-08-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_users_kakao_id_users_conversion_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='카카오 ID'),
        ),
    ]
