# Generated by Django 5.2.4 on 2026-08-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_conversion_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
