# Generated by Django 5.2.4 on 2026-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_users_is_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='kakao_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='카카오 액세스 토큰'),
        ),
        migrations.AddField(
            model_name='users',
            name='kakao_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='카카오 리프레시 토큰'),
        ),
    ]
