# Generated by Django 5.2.4 on 2026-08-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_users_is_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='credit_grade',
            field=models.CharField(default='LEVEL_0', help_text='LEVEL_0 ~ LEVEL_4 등급키 저장', max_length=20, verbose_name='신용 등급'),
        ),
    ]
