# Generated by Django 5.2.4 on 2026-08-14 11:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_users_kakao_access_token_users_kakao_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='conversion_base',
            field=models.DecimalField(decimal_places=6, default=Decimal('360'), help_text='선택한 단위 1개를 얻는 데 필요한 분. 예: 책 1권=360, 운동 1회=40. 환산 = (분 ÷ 이 값)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'), message='값이 올바르지 않습니다.')], verbose_name='환산 기준(분)'),
        ),
    ]
