# Generated by Django 5.2.4 on 2026-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_users_credit_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='conversion_units_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='사용자가 입력한 "1시간에 N개" 원본값. 표시 전용(왕복 변환 오차 방지). 계산은 conversion_base 사용.', max_digits=12, null=True, verbose_name='1시간당 활동량(입력 원본)'),
        ),
    ]
