# Generated by Django 5.2.4 on 2026-08-01 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='크루명')),
                ('invite_code', models.CharField(max_length=10, unique=True, verbose_name='초대 코드')),
                ('status', models.CharField(default='WAITING', max_length=10, verbose_name='상태')),
            ],
            options={
                'db_table': 'crew',
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='가입일')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='crew.crew')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crew_member',
                'unique_together': {('crew', 'users')},
            },
        ),
    ]
