# Generated by Django 5.2.16 on 2026-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='status',
            field=models.CharField(choices=[('WAITING', '대기중'), ('ACTIVE', '활성')], default='WAITING', max_length=10, verbose_name='상태'),
        ),
    ]
