# Generated by Django 5.1.15 on 2026-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='status',
            field=models.CharField(default='WAITING', max_length=10, verbose_name='상태'),
        ),
    ]
