# Generated by Django 5.2.16 on 2026-08-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_crew_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_minutes', models.PositiveIntegerField(default=1200, verbose_name='목표 시간(분)')),
                ('reward_text', models.CharField(blank=True, max_length=100, verbose_name='보상 문구')),
                ('crew', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='crew.crew')),
            ],
            options={
                'db_table': 'crew_goal',
            },
        ),
    ]
