# Generated by Django 5.2.4 on 2026-08-10 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_crewgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('earn', '벌이'), ('spend', '과예산 지출'), ('cheer', '응원'), ('close', '마감')], max_length=10)),
                ('message', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to='crew.crew')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_events_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['crew', '-created_at'], name='feed_event_crew_id_955f68_idx')],
            },
        ),
    ]
