# Generated by Django 5.2.16 on 2026-08-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_crewgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='character',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='캐릭터'),
        ),
    ]
