# Generated by Django 5.2.4 on 2026-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0005_feedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='character',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='캐릭터'),
        ),
    ]
