# Generated by Django 5.2.4 on 2026-08-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0006_crewmember_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedevent',
            name='event_type',
            field=models.CharField(choices=[('earn', '벌이'), ('spend', '과예산 지출'), ('cheer', '응원'), ('close', '마감'), ('leave', '탈퇴'), ('kick', '내보내기')], max_length=10),
        ),
    ]
