# Generated by Django 5.2.4 on 2026-08-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0007_alter_feedevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewmember',
            name='character',
        ),
    ]
